sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

git:
  depth: 10

script:
  - cargo clean
  - cargo check
  - cargo check --no-default-features
  - cargo test
  - cargo bench --no-run
  - cargo bench --no-default-features --no-run

after_success:
  - ./after-success.sh
