[package]
name = "mathbench"
version = "0.1.9"
authors = ["Cameron Hart <cameron.hart@gmail.com>"]
edition = "2018"

[features]
# defaults can be disabled for benchmarks but are required for tests
default = ["cgmath", "euclid", "nalgebra", "vek"]

[dependencies]
mint = "0.5.1"
rand = { version = "~0.7", default-features = false }
rand_xoshiro = "~0.4"

[dependencies.glam]
version = "0.8.2"
features = ["mint", "rand", "debug-glam-assert"]
# a lot of random data generation uses glam, so can't be optional yet
# optional = true

[dependencies.nalgebra]
version = "0.19.0"
features = ["std", "mint"]
optional = true

[dependencies.cgmath]
version = "0.17.0"
features = ["mint"]
optional = true

[dependencies.euclid]
version = "0.20.3"
features = ["mint"]
optional = true

[dependencies.vek]
version = "0.9.10"
features = ["mint"]
optional = true

[dependencies.pathfinder_geometry]
version = "0.3.0"
optional = true

[dev-dependencies]
criterion = "0.3.0"

# [patch.crates-io]
# glam = { path = "../glam-rs" }

[[bench]]
name = "eulerbench"
harness = false

[[bench]]
name = "quatbench"
harness = false

[[bench]]
name = "mat2bench"
harness = false

[[bench]]
name = "mat3bench"
harness = false

[[bench]]
name = "mat4bench"
harness = false

[[bench]]
name = "transform"
harness = false

[[bench]]
name = "vecbench"
harness = false

[profile.bench]
debug = true
# lto = true
