[package]
name = "mathbench"
version = "0.1.9"
authors = ["Cameron Hart <cameron.hart@gmail.com>"]
edition = "2018"

[dependencies]
mint = "0.5.1"
rand = { version = "~0.7", default-features = false }
rand_xoshiro = "~0.4"

[dependencies.glam]
version = "0.8.1"
default-features = false
features = ["mint", "rand"]

[dependencies.nalgebra]
version = "0.19.0"
default-features = false
features = ["std", "mint"]

[dependencies.cgmath]
version = "0.17.0"
default-features = false
features = ["mint"]

[dependencies.euclid]
version = "0.20.3"
features = ["mint"]

[dev-dependencies]
criterion = "0.3.0"

# [patch.crates-io]
# glam = { path = "../glam-rs" }

[[bench]]
name = "eulerbench"
harness = false

[[bench]]
name = "quatbench"
harness = false

[[bench]]
name = "mat2bench"
harness = false

[[bench]]
name = "mat3bench"
harness = false

[[bench]]
name = "mat4bench"
harness = false

[[bench]]
name = "transform"
harness = false

[[bench]]
name = "vecbench"
harness = false

[profile.bench]
debug = true
# lto = true
