name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Clean
        run: cargo clean

      - name: Check with pathfinder_geometry feature
        run: cargo check --features pathfinder_geometry

      - name: Check without default features
        run: cargo check --no-default-features

      - name: Run tests
        run: cargo test

      - name: Benchmark with pathfinder_geometry feature
        run: cargo bench --no-run --features pathfinder_geometry

      - name: Benchmark without default features
        run: cargo bench --no-default-features --no-run

      - name: Run after-success.sh script
        run: ./after-success.sh
